version: "3"
services:
  diary-api:
    container_name: diary-api
    image: diary-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
